version: '3.8'
services:
  db:
    image: mysql:8.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: unigpt
      MYSQL_PASSWORD: unigpt
      MYSQL_DATABASE: unigpt_chat
