spring:
  application:
    name: unigpt_bot
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    redis:
      host: 172.17.0.1
      port: 6379
logging:
  level:
    org.springframework.web.socket: DEBUG

server:
   port: 8080

services:
  user-service:
    url: ${USER_SERVICE_URL}
  chat-service:
    url: ${CHAT_SERVICE_URL}
  plugin-service:
    url: ${PLUGIN_SERVICE_URL}