spring:
  # servlet:
  #   multipart:
  #     max-file-size: 10MB
  #     max-request-size: 10MB
  # web:
  #   resources:
  #     static-locations: file:./src/main/resources/static/
  application:
    name: unigpt
  datasource:
    url: jdbc:mysql://localhost:3306/unigpt_chat
    username: unigpt
    password: unigpt
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  # data:
  #   mongodb:
  #     uri: mongodb://bleaves:bleaves@124.70.222.207:27017/file_db
  #     database: file_db
logging:
  level:
    org.springframework.web.socket: DEBUG

server:
   port: 8080


postgres:
  host: ${POSTGRES_HOST:124.70.222.207}
  port: ${POSTGRES_PORT:5432}
  database: ${POSTGRES_DB:mydatabase}
  username: ${POSTGRES_USER:bleaves}
  password: ${POSTGRES_PASSWORD:bleaves}